"""Constants."""

HTTP_TIMEOUT = 15

STATUS_CODE_403 = 403
# The lowest status a protocol treats as the remote side reporting failure.
HTTP_ERROR_STATUS = 400

CIRCUIT_BREAKER_RETRY = 5
CIRCUIT_BREAKER_TIMEOUT = 60
CIRCUIT_BREAKER_DELAY = 0
CIRCUIT_BREAKER_MAX_DELAY = 0
CHUNK_SIZE_CONSTANT = 1024
